from __future__ import annotations

RATE_LIMIT_STATUS_CODES = frozenset({429, 509})
RETRYABLE_SERVER_STATUS_CODES = frozenset({500, 502, 503, 504})
RETRYABLE_STATUS_CODES = RATE_LIMIT_STATUS_CODES | RETRYABLE_SERVER_STATUS_CODES

__all__ = [
    "RATE_LIMIT_STATUS_CODES",
    "RETRYABLE_SERVER_STATUS_CODES",
    "RETRYABLE_STATUS_CODES",
]
