from __future__ import annotations

import argparse
import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE = PROJECT_ROOT / "specifications" / "request-matrix-v1.1.60.json"
OUTPUT = PROJECT_ROOT / "src" / "apisdkopti24" / "request_metadata.py"


def render_request_metadata(source: Path = SOURCE) -> str:
    entries = json.loads(source.read_text(encoding="utf-8"))
    names = [entry["operation"] for entry in entries]
    if len(names) != len(set(names)):
        raise ValueError("request metadata source contains duplicate operation names")

    lines = [
        "# Generated by scripts/generate_request_metadata.py.",
        "# Source: specifications/request-matrix-v1.1.60.json.",
        "# Do not edit this file manually.",
        "from __future__ import annotations",
        "",
        "from .requests import RequestContract",
        "",
        "_REQUEST_CONTRACTS: dict[str, RequestContract] = {",
    ]
    for entry in sorted(entries, key=lambda item: item["operation"]):
        if entry["json_body"] is not None:
            body_kind = "json"
        elif entry["form"] is not None:
            body_kind = "form"
        else:
            body_kind = "none"
        locations = tuple(sorted(entry["contract_locations"]))
        request_models = tuple(entry.get("request_models", ()))
        lines.extend(
            [
                f'    {entry["operation"]!r}: RequestContract(',
                f'        has_path={bool(entry["path_params"])!r},',
                f'        has_query={bool(entry["query"])!r},',
                f'        body_kind={body_kind!r},',
                f"        contract_locations=frozenset({locations!r}),",
                f"        request_models={request_models!r},",
                "    ),",
            ]
        )
    lines.extend(
        [
            "}",
            "",
            "",
            "def request_spec_for(name: str) -> RequestContract:",
            "    try:",
            "        return _REQUEST_CONTRACTS[name]",
            "    except KeyError as exc:",
            '        raise KeyError(f"Request metadata is not generated for {name!r}") from exc',
            "",
            "",
            '__all__ = ["request_spec_for"]',
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate runtime request metadata")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_request_metadata()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("request_metadata.py is out of date; run this generator")
        print("Runtime request metadata is up to date")
        return
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Generated request metadata for {rendered.count('RequestContract(')} operations")


if __name__ == "__main__":
    main()
