from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import black

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "specifications" / "operation-catalog.json"
ENDPOINTS = ROOT / "src" / "apisdkopti24" / "endpoints.py"
REQUESTS = ROOT / "src" / "apisdkopti24" / "request_metadata.py"
BEGIN = "# BEGIN GENERATED OPERATION METADATA"
END = "# END GENERATED OPERATION METADATA"


def load_operations(source: Path = SOURCE) -> list[dict[str, Any]]:
    document = json.loads(source.read_text(encoding="utf-8"))
    if document.get("schema_version") != 1:
        raise ValueError("unsupported operation catalog schema")
    operations = document.get("operations")
    if not isinstance(operations, list):
        raise ValueError("operation catalog must contain an operations list")
    names = [item["name"] for item in operations]
    if len(names) != len(set(names)):
        raise ValueError("operation catalog contains duplicate names")
    return operations


def render_endpoint_block(source: Path = SOURCE) -> str:
    lines = [BEGIN, "OPERATION_METADATA = ("]
    for item in load_operations(source):
        routes = item["routes"]
        primary = routes[0]
        lines += [
            "    endpoint(",
            f"        {item['name']!r}, {item['domain']!r},",
            f"        {primary['http_method']!r}, {primary['endpoint']!r},",
            f"        {primary['api_version']!r},",
            f"        demo={primary['demo_available']!r},",
            f"        timeout={item['timeout_class']!r}, retry={item['retry_class']!r},",
            f"        requires_session={item['requires_session']!r},",
        ]
        if primary.get("external_code") is not None:
            lines += [
                f"        external_code={primary['external_code']!r},",
                f"        billable={primary['billable']!r},",
            ]
        lines.append(f"        idempotent={item['idempotent']!r},")
        if len(routes) > 1:
            lines.append("        variants=(")
            for variant in routes[1:]:
                lines += [
                    "            route(",
                    f"                {variant['http_method']!r}, {variant['endpoint']!r},",
                    f"                {variant['api_version']!r}, demo={variant['demo_available']!r},",
                    f"                name={variant['name']!r},",
                ]
                if variant.get("external_code") is not None:
                    lines += [
                        f"                external_code={variant['external_code']!r},",
                        f"                billable={variant['billable']!r},",
                    ]
                lines.append("            ),")
            lines.append("        ),")
        lines.append("    ),")
    lines += [")", END]
    return "\n".join(lines)


def render_endpoints(current: str, source: Path = SOURCE) -> str:
    before, found, remainder = current.partition(BEGIN)
    if not found:
        raise ValueError("endpoints.py is missing its generated marker")
    _, found, after = remainder.partition(END)
    if not found:
        raise ValueError("endpoints.py is missing its generated end marker")
    rendered = before + render_endpoint_block(source) + after
    return black.format_file_contents(
        rendered,
        fast=True,
        mode=black.FileMode(line_length=100, string_normalization=False),
    )


def render_request_metadata(source: Path = SOURCE) -> str:
    lines = [
        "# Generated by scripts/generate_request_metadata.py.",
        "# Source: specifications/operation-catalog.json.",
        "# Do not edit this file manually.",
        "from __future__ import annotations",
        "",
        "from .requests import RequestContract",
        "",
        "_REQUEST_CONTRACTS: dict[str, RequestContract] = {",
    ]
    for item in load_operations(source):
        request = item["request"]
        locations = tuple(request["contract_locations"])
        request_models = tuple(request.get("request_models", ()))
        lines += [
            f"    {item['name']!r}: RequestContract(",
            f"        has_path={request['has_path']!r},",
            f"        has_query={request['has_query']!r},",
            f"        body_kind={request['body_kind']!r},",
            f"        contract_locations=frozenset({locations!r}),",
            f"        request_models={request_models!r},",
            "    ),",
        ]
    lines += [
        "}",
        "",
        "",
        "def request_spec_for(name: str) -> RequestContract:",
        "    try:",
        "        return _REQUEST_CONTRACTS[name]",
        "    except KeyError as exc:",
        "        raise KeyError(f'Request metadata is not generated for {name!r}') from exc",
        "",
        "",
        "__all__ = ['request_spec_for']",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate runtime operation metadata")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    current_endpoints = ENDPOINTS.read_text(encoding="utf-8")
    rendered_endpoints = render_endpoints(current_endpoints)
    rendered_requests = render_request_metadata()
    if args.check:
        if (
            current_endpoints != rendered_endpoints
            or REQUESTS.read_text(encoding="utf-8") != rendered_requests
        ):
            raise SystemExit("runtime operation metadata is out of date; run this generator")
        print("Runtime operation metadata is up to date")
        return
    ENDPOINTS.write_text(rendered_endpoints, encoding="utf-8")
    REQUESTS.write_text(rendered_requests, encoding="utf-8")
    print(f"Generated metadata for {len(load_operations())} operations")


if __name__ == "__main__":
    main()
